name: website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}
        aws-session-token: ${{ secrets.SESSIONTOKEN }}
        aws-region: us-east-1

    - name: Deploy static website
      run: aws s3 sync . s3://githubactionayush --delete
